// Base d'ingrédients d'Épi.
// niveau : "danger" (contient du gluten) | "warn" (à vérifier sur l'étiquette) | "safe" (sans gluten)
// Sources : AFDIAG (Association Française Des Intolérants Au Gluten), Ameli.fr (Assurance Maladie),
// Règlement (UE) n°828/2014 relatif aux denrées alimentaires pour personnes intolérantes au gluten.

const INGREDIENTS = [
  // --- Céréales contenant du gluten ---
  { id:"ble", noms:["blé","froment","farine de blé","farine de froment"], categorie:"Céréales", niveau:"danger",
    note:"Céréale qui contient naturellement du gluten.",
    source:"Ameli.fr", sourceUrl:"https://www.ameli.fr/assure/sante/themes/intolerance-gluten-maladie-coeliaque/definition-causes-facteurs-favorisants" },
  { id:"epeautre", noms:["épeautre","petit épeautre"], categorie:"Céréales", niveau:"danger",
    note:"Variété de blé, contient du gluten.",
    source:"Ameli.fr", sourceUrl:"https://www.ameli.fr/assure/sante/themes/intolerance-gluten-maladie-coeliaque/definition-causes-facteurs-favorisants" },
  { id:"kamut", noms:["kamut","blé de khorasan"], categorie:"Céréales", niveau:"danger",
    note:"Variété ancienne de blé, contient du gluten.",
    source:"Ameli.fr", sourceUrl:"https://www.ameli.fr/assure/sante/themes/intolerance-gluten-maladie-coeliaque/definition-causes-facteurs-favorisants" },
  { id:"seigle", noms:["seigle"], categorie:"Céréales", niveau:"danger",
    note:"Céréale à gluten, utilisée notamment dans le pain noir.",
    source:"Ameli.fr", sourceUrl:"https://www.ameli.fr/assure/sante/themes/intolerance-gluten-maladie-coeliaque/definition-causes-facteurs-favorisants" },
  { id:"orge", noms:["orge"], categorie:"Céréales", niveau:"danger",
    note:"Céréale à gluten, base du malt et de la bière.",
    source:"Ameli.fr", sourceUrl:"https://www.ameli.fr/assure/sante/themes/intolerance-gluten-maladie-coeliaque/definition-causes-facteurs-favorisants" },
  { id:"triticale", noms:["triticale"], categorie:"Céréales", niveau:"danger",
    note:"Hybride de blé et de seigle, contient du gluten.",
    source:"Ameli.fr", sourceUrl:"https://www.ameli.fr/assure/sante/themes/intolerance-gluten-maladie-coeliaque/definition-causes-facteurs-favorisants" },
  { id:"boulgour", noms:["boulgour"], categorie:"Céréales", niveau:"danger",
    note:"Blé concassé précuit, contient du gluten.",
    source:"AFDIAG" },
  { id:"couscous", noms:["couscous","semoule de blé","semoule"], categorie:"Céréales", niveau:"danger",
    note:"Semoule de blé dur roulée, contient du gluten.",
    source:"AFDIAG" },
  { id:"pates", noms:["pâtes","pâtes alimentaires","spaghetti","macaroni","tagliatelles"], categorie:"Céréales", niveau:"danger",
    note:"Fabriquées à partir de blé, sauf mention explicite « sans gluten ».",
    source:"AFDIAG" },
  { id:"pain", noms:["pain","baguette","pain de mie"], categorie:"Céréales", niveau:"danger",
    note:"À base de farine de blé (ou autre céréale à gluten), sauf mention « sans gluten ».",
    source:"AFDIAG" },
  { id:"chapelure", noms:["chapelure","panure"], categorie:"Céréales", niveau:"danger",
    note:"Faite à partir de pain, donc de blé.",
    source:"AFDIAG" },
  { id:"biscuits", noms:["biscuits","gâteaux","pâtisserie","viennoiserie"], categorie:"Céréales", niveau:"danger",
    note:"À base de farine de blé dans leur recette classique.",
    source:"AFDIAG" },

  // --- Dérivés et sources cachées ---
  { id:"malt", noms:["malt","sirop de malt","arôme de malt","extrait de malt"], categorie:"Dérivés", niveau:"danger",
    note:"Issu de l'orge germée, contient du gluten.",
    source:"AFDIAG" },
  { id:"biere", noms:["bière"], categorie:"Boissons", niveau:"danger",
    note:"Fabriquée à partir d'orge maltée.",
    source:"AFDIAG" },
  { id:"vinaigre-malt", noms:["vinaigre de malt"], categorie:"Dérivés", niveau:"danger",
    note:"Issu de l'orge maltée, contient du gluten.",
    source:"AFDIAG" },
  { id:"sauce-soja", noms:["sauce soja","sauce soya"], categorie:"Sauces", niveau:"warn",
    note:"Souvent fermentée avec du blé. Les versions « tamari » sont en général sans blé — à confirmer sur l'étiquette.",
    source:"AFDIAG" },
  { id:"avoine", noms:["avoine","flocons d'avoine"], categorie:"Céréales", niveau:"warn",
    note:"Ne contient pas de gluten à l'état pur, mais très souvent contaminée par du blé pendant la culture ou le traitement. Seule l'avoine certifiée « sans gluten » (logo épi barré) est fiable pour un régime strict.",
    source:"Ameli.fr", sourceUrl:"https://www.ameli.fr/assure/sante/themes/intolerance-gluten-maladie-coeliaque/regime-alimentaire" },
  { id:"amidon-modifie", noms:["amidon modifié","amidon de blé"], categorie:"Additifs", niveau:"warn",
    note:"Peut provenir de blé, de maïs ou de pomme de terre selon le fabricant. L'origine doit être précisée sur l'étiquette si c'est du blé.",
    source:"AFDIAG" },
  { id:"farine-generique", noms:["farine"], categorie:"Céréales", niveau:"warn",
    note:"Le terme seul est ambigu : vérifier la céréale d'origine (blé = gluten ; riz, maïs, sarrasin = sans gluten).",
    source:"AFDIAG" },
  { id:"figues-sechees", noms:["figues séchées","figue sèche"], categorie:"Fruits transformés", niveau:"warn",
    note:"Souvent roulées dans la farine avant emballage pour éviter qu'elles collent entre elles.",
    source:"AFDIAG" },
  { id:"yaourt-aromatise", noms:["yaourt aromatisé","yaourt allégé","crème dessert"], categorie:"Produits laitiers", niveau:"warn",
    note:"Peuvent contenir des agents de texture à base d'amidon de blé non modifié.",
    source:"AFDIAG" },
  { id:"charcuterie-industrielle", noms:["charcuterie industrielle","saucisse industrielle","plat préparé","sauce industrielle"], categorie:"Produits transformés", niveau:"warn",
    note:"Le gluten est parfois utilisé comme liant ou agent de texture dans l'industrie agroalimentaire.",
    source:"AFDIAG" },
  { id:"fromage-fondu", noms:["fromage fondu","fromage tartinable","fromage à tartiner"], categorie:"Produits laitiers", niveau:"warn",
    note:"Les additifs de texture utilisés varient selon la marque — à vérifier sur l'étiquette.",
    source:"AFDIAG" },

  // --- Naturellement sans gluten ---
  { id:"riz", noms:["riz"], categorie:"Céréales", niveau:"safe",
    note:"Naturellement sans gluten.",
    source:"Ameli.fr", sourceUrl:"https://www.ameli.fr/assure/sante/themes/intolerance-gluten-maladie-coeliaque/definition-causes-facteurs-favorisants" },
  { id:"mais", noms:["maïs","farine de maïs","polenta"], categorie:"Céréales", niveau:"safe",
    note:"Naturellement sans gluten.",
    source:"Ameli.fr", sourceUrl:"https://www.ameli.fr/assure/sante/themes/intolerance-gluten-maladie-coeliaque/definition-causes-facteurs-favorisants" },
  { id:"quinoa", noms:["quinoa"], categorie:"Céréales", niveau:"safe",
    note:"Naturellement sans gluten.",
    source:"Ameli.fr", sourceUrl:"https://www.ameli.fr/assure/sante/themes/intolerance-gluten-maladie-coeliaque/definition-causes-facteurs-favorisants" },
  { id:"millet", noms:["millet"], categorie:"Céréales", niveau:"safe",
    note:"Naturellement sans gluten.",
    source:"Ameli.fr", sourceUrl:"https://www.ameli.fr/assure/sante/themes/intolerance-gluten-maladie-coeliaque/definition-causes-facteurs-favorisants" },
  { id:"sorgho", noms:["sorgho"], categorie:"Céréales", niveau:"safe",
    note:"Naturellement sans gluten.",
    source:"Ameli.fr", sourceUrl:"https://www.ameli.fr/assure/sante/themes/intolerance-gluten-maladie-coeliaque/definition-causes-facteurs-favorisants" },
  { id:"sarrasin", noms:["sarrasin","farine de sarrasin","blé noir"], categorie:"Céréales", niveau:"safe",
    note:"Malgré son nom, ne contient pas de gluten.",
    source:"AFDIAG" },
  { id:"sirop-glucose", noms:["sirop de glucose","dextrose","maltodextrine"], categorie:"Additifs", niveau:"safe",
    note:"Même fabriqué à partir de blé, le gluten est éliminé lors de la transformation : exempté d'étiquetage allergène par la réglementation européenne.",
    source:"Règlement (UE) n°828/2014" },
  { id:"legumineuses", noms:["lentilles","pois chiches","haricots secs","haricots blancs","haricots rouges"], categorie:"Légumineuses", niveau:"safe",
    note:"Naturellement sans gluten.",
    source:"AFDIAG" },
  { id:"pomme-de-terre", noms:["pomme de terre","patate","patate douce","topinambour"], categorie:"Légumes", niveau:"safe",
    note:"Aliment brut, naturellement sans gluten.",
    source:"AFDIAG" },
  { id:"legumes", noms:["légume","courgette","tomate","carotte","oignon","poivron","aubergine","brocoli","salade","épinard","poireau"], categorie:"Légumes", niveau:"safe",
    note:"Aliment brut, naturellement sans gluten.",
    source:"AFDIAG" },
  { id:"fruits", noms:["fruit","pomme","banane","orange","poire","fraise","raisin","citron"], categorie:"Fruits", niveau:"safe",
    note:"Aliment brut, naturellement sans gluten.",
    source:"AFDIAG" },
  { id:"viande-fraiche", noms:["poulet","bœuf","porc","agneau","dinde","veau"], categorie:"Viandes", niveau:"safe",
    note:"Viande fraîche non transformée, sans gluten. Attention si panée, marinée ou en préparation industrielle.",
    source:"AFDIAG" },
  { id:"poisson", noms:["poisson","saumon","cabillaud","thon","fruits de mer","crevette"], categorie:"Poissons", niveau:"safe",
    note:"Frais et non transformé, sans gluten. Attention si pané ou en préparation industrielle.",
    source:"AFDIAG" },
  { id:"oeuf", noms:["œuf","oeuf","oeufs","œufs"], categorie:"Autres", niveau:"safe",
    note:"Aliment brut, naturellement sans gluten.",
    source:"AFDIAG" },
  { id:"lait", noms:["lait"], categorie:"Produits laitiers", niveau:"safe",
    note:"Naturellement sans gluten.",
    source:"AFDIAG" },
  { id:"yaourt-nature", noms:["yaourt nature","yaourt"], categorie:"Produits laitiers", niveau:"safe",
    note:"Le yaourt nature est naturellement sans gluten (contrairement aux versions aromatisées).",
    source:"AFDIAG" },
  { id:"fromage", noms:["fromage","fromage traditionnel"], categorie:"Produits laitiers", niveau:"safe",
    note:"Les fromages traditionnels sont naturellement sans gluten.",
    source:"AFDIAG" },
  { id:"huile-olive", noms:["huile d'olive","huile","huile de tournesol"], categorie:"Autres", niveau:"safe",
    note:"Naturellement sans gluten.",
    source:"AFDIAG" },
  { id:"vinaigre-vin", noms:["vinaigre de vin","vinaigre de cidre","vinaigre balsamique"], categorie:"Autres", niveau:"safe",
    note:"Contrairement au vinaigre de malt, ces vinaigres sont sans gluten.",
    source:"AFDIAG" },
  { id:"sel-poivre-sucre", noms:["sel","poivre","sucre","miel"], categorie:"Autres", niveau:"safe",
    note:"Naturellement sans gluten.",
    source:"AFDIAG" },
  { id:"levure", noms:["levure de boulanger","levure chimique","levure de bière"], categorie:"Autres", niveau:"safe",
    note:"Naturellement sans gluten (à ne pas confondre avec le malt, lui aussi parfois appelé « levure »).",
    source:"AFDIAG" },
];
